server:
  port: 8088
app:
  name: 'Spring Boot Vaadin'
  shortName: 'Spring Boot Vaadin'
  description: 'Spring Boot Vaadin application'
spring:
  profiles:
    active: local,dev,test,prod
  devtools:
    add-properties: false
  datasource:
    initialization-mode: always
    # Use MariaDB for persistence
    #driverClassName: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/database
    #username: 'database'
    #password: 'database'
    
    # Use SQLite for persistence, additionally to the following lines add the line under jpa (see lines below)
    #driverClassName: org.sqlite.JDBC
    #url: "jdbc:sqlite:file:./spvDb?cache=shared"
    #username=sa
    #password=sa
    
    # use HSQlDB for persistence
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:sbvHSQLDB
    username: 'sa'
    password: 'sa'
  jpa:
    #database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
    show-sql: false
    #show-sql: true
  sql:
    init:
      mode: never
  mustache:
    check-template-location: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      atmosphere: INFO
      hibernate: INFO
      springframework:
        web: INFO
    guru:
      springframework:
        controllers: DEBUG
jwt:
    auth:
      secret: 'J6GOtcwC2NJI1l0VkHu20PacPFGTxpirBxWwynoHjsc='
