server:
  port: 8085
app:
  name: 'Spring Boot Vaadin'
  shortName: 'Spring Boot Vaadin'
  description: 'Spring Boot Vaadin application'
spring:
  profiles:
    active: local,dev,test,prod
  devtools:
    add-properties: false
  datasource:
    initialization-mode: always
    #driverClassName: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/database
    #username: 'database'
    #password: 'database'
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:springbootvaadinHSQLDB
    username: 'sa'
    password: 'sa'
  #jpa
    #database-platform: org.hibernate.community.dialect.SQLiteDialect
  #datasource
    #driverClassName: org.sqlite.JDBC
    #url: "jdbc:sqlite:file:./kontorDb?cache=shared"
    #username=sa
    #password=sa
  jpa:
    defer-datasource-initialization: true
    #hibernate.ddl-auto=create-drop
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
      #show-sql: false
    show-sql: true
  sql:
    init:
      mode: never
  mustache:
    check-template-location: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      atmosphere: INFO
      hibernate: INFO
      springframework:
        web: INFO
    guru:
      springframework:
        controllers: DEBUG
jwt:
    auth:
      secret: 'J6GOtcwC2NJI1l0VkHu20PacPFGTxpirBxWwynoHjsc='
mail:
    protocol: 'imap'
    host: 'corky.svpdata.eu'
    port: 143
    userName: 'thomas.peetz@thpeetz.de'
    password: 'fS9f4JYDIO7A'
    starttls: true
